
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rtomyj/microservices
          searchPaths: 'cloud-config-data/{application}/{application}-{profile}'

server:
  port: 8081